spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:symptomdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

server:
  port: 8081

  
